"""Add request_type to credit_requests

Revision ID: 2455f9b2ff71
Revises: dedc126561b9
Create Date: 2026-09-17 16:28:01.914597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2455f9b2ff71'
down_revision: Union[str, None] = 'dedc126561b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_type', sa.String(length=20), server_default='Deposit', nullable=False))
        batch_op.add_column(sa.Column('payment_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_requests', schema=None) as batch_op:
        batch_op.drop_column('payment_details')
        batch_op.drop_column('request_type')

    # ### end Alembic commands ###
