"""add visible_to_user to credit_ledger

Revision ID: 873759b1e2e9
Revises: 2455f9b2ff71
Create Date: 2026-09-21 22:22:40.063959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873759b1e2e9'
down_revision: Union[str, None] = '2455f9b2ff71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visible_to_user', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_column('visible_to_user')

    # ### end Alembic commands ###
