"""rename student to user

Revision ID: 8bdcf2fe512b
Revises: 
Create Date: 2026-09-15 12:55:04.082047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bdcf2fe512b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('digit_length', sa.Integer(), nullable=False),
    sa.Column('classification_rule', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_types_code'), ['code'], unique=True)

    op.create_table('homepage_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_categories_slug'), ['slug'], unique=True)

    op.create_table('scrolling_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('credit_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=30), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('educational_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_type_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('how_it_works', sa.Text(), nullable=False),
    sa.Column('example', sa.Text(), nullable=False),
    sa.Column('probability_explanation', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=True),
    sa.Column('closing_time', sa.Time(), nullable=True),
    sa.Column('result_time', sa.Time(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['market_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_markets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_markets_slug'), ['slug'], unique=True)

    op.create_table('support_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_queries_user_id'), ['user_id'], unique=False)

    op.create_table('starline_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=60), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('cutoff_time', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('starline_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_starline_slots_market_id'), ['market_id'], unique=False)

    op.create_table('support_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['support_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_support_messages_query_id'), ['query_id'], unique=False)

    op.create_table('game_type_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_credits', sa.Integer(), nullable=False),
    sa.Column('max_credits', sa.Integer(), nullable=False),
    sa.Column('bulk_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_bulk_selections', sa.Integer(), nullable=False),
    sa.Column('same_amount_allowed', sa.Boolean(), nullable=False),
    sa.Column('individual_amount_allowed', sa.Boolean(), nullable=False),
    sa.Column('duplicate_selection_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['starline_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_type_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_type_configs_game_type_id'), ['game_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_type_configs_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_type_configs_slot_id'), ['slot_id'], unique=False)

    op.create_table('market_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('open_panna', sa.String(length=3), nullable=True),
    sa.Column('open_ank', sa.String(length=1), nullable=True),
    sa.Column('close_panna', sa.String(length=3), nullable=True),
    sa.Column('close_ank', sa.String(length=1), nullable=True),
    sa.Column('jodi', sa.String(length=2), nullable=True),
    sa.Column('single_result', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('corrected_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['corrected_from_id'], ['market_results.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['published_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['starline_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_results_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_results_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_results_slot_id'), ['slot_id'], unique=False)

    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['starline_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rates_game_type_id'), ['game_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rates_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rates_slot_id'), ['slot_id'], unique=False)

    op.create_table('simulation_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('created_via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['starline_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_batches_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_batches_user_id'), ['user_id'], unique=False)

    op.create_table('simulation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('game_type_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=True),
    sa.Column('selection', sa.String(length=10), nullable=False),
    sa.Column('simulated_credits', sa.Integer(), nullable=False),
    sa.Column('simulated_rate', sa.Integer(), nullable=False),
    sa.Column('simulated_return', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['simulation_batches.id'], ),
    sa.ForeignKeyConstraint(['game_type_id'], ['game_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['market_results.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['starline_slots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_entries_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_entries_market_id'), ['market_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_entries_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('simulation_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_entries_market_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_entries_batch_id'))

    op.drop_table('simulation_entries')
    with op.batch_alter_table('simulation_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_batches_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_batches_market_id'))

    op.drop_table('simulation_batches')
    with op.batch_alter_table('rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rates_slot_id'))
        batch_op.drop_index(batch_op.f('ix_rates_market_id'))
        batch_op.drop_index(batch_op.f('ix_rates_game_type_id'))

    op.drop_table('rates')
    with op.batch_alter_table('market_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_results_slot_id'))
        batch_op.drop_index(batch_op.f('ix_market_results_market_id'))
        batch_op.drop_index(batch_op.f('ix_market_results_date'))

    op.drop_table('market_results')
    with op.batch_alter_table('game_type_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_type_configs_slot_id'))
        batch_op.drop_index(batch_op.f('ix_game_type_configs_market_id'))
        batch_op.drop_index(batch_op.f('ix_game_type_configs_game_type_id'))

    op.drop_table('game_type_configs')
    with op.batch_alter_table('support_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_messages_query_id'))

    op.drop_table('support_messages')
    with op.batch_alter_table('starline_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_starline_slots_market_id'))

    op.drop_table('starline_slots')
    with op.batch_alter_table('support_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_queries_user_id'))

    op.drop_table('support_queries')
    with op.batch_alter_table('markets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_markets_slug'))
        batch_op.drop_index(batch_op.f('ix_markets_category_id'))

    op.drop_table('markets')
    op.drop_table('educational_content')
    with op.batch_alter_table('credit_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_credit_ledger_created_at'))

    op.drop_table('credit_ledger')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_key'))

    op.drop_table('site_settings')
    op.drop_table('scrolling_messages')
    with op.batch_alter_table('market_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_categories_slug'))

    op.drop_table('market_categories')
    op.drop_table('homepage_banners')
    with op.batch_alter_table('game_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_types_code'))

    op.drop_table('game_types')
    op.drop_table('faqs')
    op.drop_table('audit_logs')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
