"""Add UTR and screenshot to credit requests

Revision ID: dedc126561b9
Revises: e5f8a9b0c407
Create Date: 2026-09-17 16:05:49.324465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dedc126561b9'
down_revision: Union[str, None] = 'e5f8a9b0c407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utr_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('screenshot_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_requests', schema=None) as batch_op:
        batch_op.drop_column('screenshot_url')
        batch_op.drop_column('utr_number')

    # ### end Alembic commands ###
